SELECT TITLE,	b.BOARD_ID,	REPLY_ID,	r.WRITER_ID,	r.CONTENTS,	date_format(r.CREATED_DATE,'%Y-%m-%d') as CREATED_DATE
from USED_GOODS_BOARD b join USED_GOODS_REPLY r on r.BOARD_ID=b.BOARD_ID
where b.CREATED_DATE like '%2022-10%'
order by r.CREATED_DATE, TITLE